### ISSUE TITLE
アプリケーションの設計

### ISSUE THREAD

**Issue by ShimaBee** [Yuta1122/credit_diagnosis#2]
dropboxpaperに書いた設計を写したもの

**Comment by Yuta1122** [comment]
## 利用する技術
フロントエンド => Nuxt.js
バックエンド => Rails

## 理由
- 上記した動きを簡単に実装できる。
- Rails, Nuxtを学びたい。
- すでに似たアプリケーションを同じように作っているので、早く実装できる。

**Comment by Yuta1122** [comment]
## メリット
- 動的におすすめを提示できるので、よりユーザーにあったカードを進められる。
- 取り扱うカードが増えてもそのカードにパラメータをふることで簡単に追加することができる。
- 動的にページを作るため、多くのHTMLを書かなくても良い

## デメリット
- **パラメータの振り方が難しい。(重要)**
- 動的に値を返すので、静的ファイルを返すよりはサーバーに負荷がかかる。
- 実装の難易度が少し高い

**Comment by ShimaBee** [comment]
# クレジット診断　設計

## 概要
質問に答えていくと、おすすめのクレジットカードを提案してくれるアプリケーション。


## 全体設計
1. クレジットカードそれぞれに適正年齢、ポイントのためやすさ、マイルのためやすさ、年会費というカテゴリーを持たせて、その中に適正な値を入れておく。
```
    ex)
    クレジットカードA
    - おすすめ年齢 0
    - ポイントのためやすさ 0.7
    - マイルのためやすさ 0.5
    - 年会費 0
    
    クレジットカードA の値[0,0.7,0.5,0]
```

2. ユーザーの答えた選択肢の取得。
```
    ex)
    Q1 年齢は？ 
    18 ~ 25  => 0
    
    Q2 ポイントのたまりやすさは気にしますか？
     とても気にする => 3
    
    Q3 マイルのはのたまりやすさは気にしますか？
    あまり気にしない => 1
    
    Q4 年会費は気にしますか？
    とても気にする => 0
    
    ユーザーAの回答[0,3,1,0]
```

3. ユーザーの選択肢からユーザーの趣向を表した値を算出する。
- 質問の選択肢には、それぞれ値（趣向値）が設けられています。
- 例えばQ1で18 ~ 25と答えるとそのユーザーのageカテゴリーにおける趣向値は0、Q2で気にすると答えるとそのユーザーのpointカテゴリーにおける趣向値は0.3となります。このようにage, point, mile, annual_feeの四つのカテゴリーにおけるユーザーの趣向値を算出し、カードの値と比較します。
- 今後、質問やカードが増えることを考え、趣向値の最大は1、最低は0と決めておきます。

```
    ex)
    Q1 年齢は？ 
    ⓪ 18 ~ 25 => 0
    ① 26 ~ 29 => 0.3
    ② 30 ~ 39 => 0.6
    ③ 40 ~ => 1
    
    Q2 ポイントのたまりやすさは気にしますか？
    ⓪ とても気にする => 0
    ① 気にする => 0.3
    ② あまり気にしない => 0.7
    ③ 気にしない => 1
    
    
    Q3 マイルのはのたまりやすさは気にしますか？
    ⓪ とても気にする => 0
    ① 気にする => 0.3
    ② あまり気にしない => 0.7
    ③ 気にしない => 1
    
    Q4 年会費は気にしますか？
    ⓪ とても気にする => 0
    ① 気にする => 0.3
    ② あまり気にしない => 0.7
    ③ 気にしない => 1
    
    回答から算出されたユーザーの総合趣向値[0,1,0.3,0]
```

4. それぞれのカードとユーザーのパラメータを比較して、よりマッチしたものをおすすめとして出す。


システム設計
![](https://paper-attachments.dropbox.com/s_829B56AB10559829248933B18DFDAFE724E9C3849F746E83F89F4D117700719D_1581313197902_iOS++7.jpg)

- フロントのNuxtはSPAモードで作って、バックエンドはRailsのAPIモードで作ります。
- デプロイは二つのherokuサーバを用意し、それぞれにNuxt ,Railsを分けて上げます。
- 画像は専用のサーバを設けず、Nuxtで持っておきます。
- 質問文はRails内に、yamlで書いておく。


DB設計
![](https://paper-attachments.dropbox.com/s_829B56AB10559829248933B18DFDAFE724E9C3849F746E83F89F4D117700719D_1581317837197_caerd_table.001.jpeg)

質問と選択肢


1. 年齢は？　→　(a. 18 - 25, b.26 - 29,  c.30 - 39,  d.40以上 )
2. ポイントのたまりやすさは気にしますか？　→　(a. とても気にする, b.気にする,  c.あまり気にしない,  d.気にしない )
3. マイルのはのたまりやすさは気にしますか？　→　(a. とても気にする, b.気にする,  c.あまり気にしない,  d.気にしない )
4. 年会費は気にしますか？　 →　(a. とても気にする, b.気にする,  c.あまり気にしない,  d.気にしない )


画面設計
![TOPページ](https://paper-attachments.dropbox.com/s_829B56AB10559829248933B18DFDAFE724E9C3849F746E83F89F4D117700719D_1580019935928_Card_image.003.jpeg)

![質問ページ](https://paper-attachments.dropbox.com/s_829B56AB10559829248933B18DFDAFE724E9C3849F746E83F89F4D117700719D_1580019952569_Card_image.002.jpeg)

![結果ページ](https://paper-attachments.dropbox.com/s_829B56AB10559829248933B18DFDAFE724E9C3849F746E83F89F4D117700719D_1580019974523_Card_image.004.jpeg)



マッチング方法


- 全体設計で述べたように、カードに予め与えられた値と質問に答えたユーザーの趣向値を比較し、おすすめのカードをDBから持ってくる仕組みでユーザとカードをマッチングさせます。
- しかし、カードの値とユーザの趣向値が一致するとも限らないため、DBから持ってくるカードの値に幅を持たせます。例えば、ユーザーの総合趣向値が [0, 1, 0.3, 0] である場合、引っ張ってくるカードの値は[0~0.3, 0.7~1, 0.3~0.6, 0~0.3]と言うように範囲を指定して、おすすめのカードがないと言う状態を回避します。



この設計にした理由


1. ユーザーの趣向を細かく測り、よりユーザーに合ったカードをおすすめできる。


2. カードを簡単に増やすことができる。
- カードを増やす際は、既存のカードと比較しながら、新しいカードにage, point, miles, annual_feeというカテゴリー別に値を振って、DBに保存するだけでいいので、比較的簡単にカードの追加ができます。


3. フロントエンドとバックエンドが疎結合であるため、メンテナンスが比較的しやすい。
- フロントエンドはjsonで送られてくるデータの描画を意識すれば良いので、テンプレートエンジンに縛られた書き方をしなくても良いし、バックエンドで定義された変数のことも考えなくてもよい。
- バックエンドも決まった形で送られてくる値を加工してjsonで送るだけなので、描画のためのインスタンス変数なども作らないで良い。ルーティングもフロントでやるので考えなくても良い。



フィードバック

あまり設計のことでフィードバックを得たことがないので、ものすごく有り難い。

1.趣向値が不均等な離散値であること
これは何かメリットがありますか？？あと感覚値的には
とても気にすると気にするの差分
気にしないとあまり気にしないの差分では
前者のほうが大きいように感じます。


- 趣向値はyamlで管理し、簡単に書き換えることが可能なため深く考えていなかった。(設計の段階よりも使ってもらってからの微調整の方が重要であると考えている。)
- 少数第一位以下の値を切り捨てた形で、簡単に四等分してみただけの値に設定していた。
- カードの値は最大1、だが趣向値は質問の数、内容の変更によって簡単に変更できた方が、フレキシブルでよい。カードの値はDBに入れるので、あまり頻繁に書き換えたくはないので、最大値を決める。おそらくカードの値の最大値を決めないと、質問が多くなるに連れて値のインフレが起きる。
- 選択肢の中で、趣向値が大きく変わりそうな部分に重みを持たせるという意味で、少数第二位以下の値を反映させるようにする。

ex)

    ⓪ とても気にする => 0
    ① 気にする => 0.3
    ② あまり気にしない => 0.7
    ③ 気にしない => 1


- 年齢は、整数管理でもいいかもしれない。

 

2.ユーザとカードのポイントの単純な近似値でマッチングしている理由について
ユーザが気にしない項目についてはむしろカードの値がどのようになっていても
引っ張ってくるロジックのほうが正しい気がするけどどうだろう？
※ポイントについて気にしないユーザにとってポイントがめちゃくちゃ貯まることはマイナスではないはず

単純な近似値でマッチングしている理由は、そのユーザによりカスタマイズされたカードをおすすめしたいから。確かに、ポイントを気にしない人にもポイントが溜まりやすいカードは悪くはないが、それでは多くのカードがヒットしてしまうかもしれない。ユーザの選択肢を絞るのもこのアプリの役目だと思っている。


3.単純な範囲検索ではなく、マッチ度をスコア化し、スコアが高い順にいくつ絞ってユーザに提示しては？
→ユーザの回答によっておすすめのカードが表示されないなどの懸念があるため
→カードのポイントが仮に変わったり、事情によりカードを非表示にしたり等する可能性があるため


マッチ度をスコア化
|趣向値 - カードの値 | の配列を作り、それの総和の低い順に並べる。

スコアが高い順にいくつ絞る
総和の低い順に並べたものの先頭三つのカードを取得する。
